version: "3.5"

services:
  pythonclub:
    build:
      image: ty1erdurden/pythonclub:latest
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - SLACK_CHANNEL
      - EMAIL_ADDRESS
      - GITHUB_PROFILE
      - GITHUB_API_TOKEN
    restart: on-failure
